server:
  port: ${SERVER_PORT:8080}
spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://0.0.0.0:5432/testdb}
    username: ${DATASOURCE_USERNAME:testuser}
    password: ${DATASOURCE_PASS:testpass}
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: none

    show-sql: true
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: validate
        jdbc:
          lob:
            non_contextual_creation:true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

  sql:
    init:
      mode: never
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: TRACE
jwt:
  key: ${JWT_KEY}
  access-token-expiration: 3600000
  refresh-token-expiration: 86400000